name: Build Bytecode

on:
  push:
  pull_request:
    types: [ opened, ready_for_review, reopened ]

permissions:
  contents: read

jobs:
  build:
    if: "github.event_name != 'push' || !startsWith(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew clean build
