name: Build Bytecode

on:
  push:
  pull_request:
    types: [ opened, ready_for_review, reopened ]

permissions:
  contents: read

jobs:
  build:
    if: "github.event_name != 'push' || !startsWith(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: oracle
          java-version: 24
          cache: gradle

      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew clean build
